Repository MichaelDysart/SYSC4806_Project, pull requests merged in 2020-04, with the labels that each got.

#77 [75] Add UUID link to surveys
  package-lock.json
  package.json
  src/main/java/survey/Survey.java
  src/main/java/webApp/Response.java
  src/main/java/webApp/webController.java
  src/main/js/App.js
  src/main/js/Summary.js
  src/main/js/SurveyPage.js
  src/main/js/SurveyPage.scss
  src/test/java/webApp/ResponseTest.java
  src/test/js/SurveyPage.test.js
Labels: Ready for Review

#82 Fix Bug with number summary with no answers
  package-lock.json
  src/main/js/Summary.js
  src/main/js/SurveyPage.js
Labels: bug

#84 Pi chart
  package-lock.json
  package.json
  src/main/js/Summary.js
Labels: enhancement

#87 Update umlm3
  README.md
  Resources/uml-diagram-milestone03.png
Labels: documentation

#89 Update pi chart
  package-lock.json
  package.json
  src/main/js/Summary.js
Labels: enhancement

#93 #92 separate summary
  package-lock.json
  src/main/js/CreatePage.js
  src/main/js/Summary.js
  src/main/js/SurveyPage.scss
  src/main/js/ViewPage.js
Labels: enhancement

#94 [79] Add ability to retrieve surveys by link
  package-lock.json
  src/main/java/webApp/SurveyRepository.java
  src/main/java/webApp/webController.java
  src/main/js/App.js
  src/main/js/CreatePage.js
  src/main/js/HomePage.js
  src/main/js/SurveyPage.scss
  src/main/js/ViewPage.js
  src/test/java/webApp/webControllerTest.java
  src/test/js/SurveyPage.test.js
Labels: enhancement
